FROM node:17.9-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# python2 is needed for building sqlite3
RUN apk --no-cache add --virtual .builds-deps build-base python2
RUN export PYTHON=/usr/bin/python2

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . ./

CMD ["yarn", "start"]
