version: "3.3"

services:
  cc-api-prod:
    container_name: cc-api-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - SECRET_KEY="PUT SOMETHING ELSE IN HERE!"
